require("mysterius79.remap")
require("mysterius79.packer")
require("mysterius79.Mason")
require("mysterius79.colors")
require("mysterius79.set")
require("mysterius79.treesitter")
require("mysterius79.lsp")
